// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LocalLLMChat",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "LocalLLMChat",
            targets: ["AppModule"],
            bundleIdentifier: "com.vesco.localllmchat",
            teamIdentifier: "XVUN5CYHJC",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .localNetwork(purposeString: "Local network access is required to connect to your Ollama instance.", bonjourServiceTypes: []),
                .outgoingNetworkConnections()
            ],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)